# -*- coding: utf-8 -*-
"""Novalex_Content_Plan_Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGkS0rQR1MkA8pTV45uC3NG1gKeHClha
"""

!pip install openpyxl

import pandas as pd
from datetime import timedelta

import os

os.listdir()

import os

os.listdir()

submission_file = "Novalex Submission Tracker.xlsx"
master_file = "EMA Variations Master Database.xlsx"

submissions = pd.read_excel(submission_file)
master = pd.read_excel(master_file)

print("Submission Tracker shape:", submissions.shape)
print("EMA Master Database shape:", master.shape)

display(submissions.head())
display(master.head())

submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
master.columns = master.columns.str.strip().str.replace(" ", "_")

print("Submission columns:")
print(submissions.columns.tolist())

print("\nMaster database columns:")
print(master.columns.tolist())

import pandas as pd
from datetime import timedelta

# Load files
submission_file = "Novalex Submission Tracker.xlsx"
master_file = "EMA Variations Master Database.xlsx"

submissions = pd.read_excel(submission_file)
master = pd.read_excel(master_file)

# Clean column names
submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
master.columns = master.columns.str.strip().str.replace(" ", "_")

# Basic CTD template by variation category
ctd_templates = {
    "IA": [
        ("Module 1", "1.0", "Cover Letter", "Administrative Document"),
        ("Module 1", "1.2", "Application Form", "Administrative Document"),
        ("Module 1", "1.3", "Product Information, if applicable", "Labelling Document"),
        ("Module 3", "Affected Quality Section", "Updated Quality Documentation", "CMC Document")
    ],

    "IAIN": [
        ("Module 1", "1.0", "Cover Letter", "Administrative Document"),
        ("Module 1", "1.2", "Application Form", "Administrative Document"),
        ("Module 1", "1.3", "Product Information, if applicable", "Labelling Document"),
        ("Module 3", "Affected Quality Section", "Updated Quality Documentation", "CMC Document")
    ],

    "IB": [
        ("Module 1", "1.0", "Cover Letter", "Administrative Document"),
        ("Module 1", "1.2", "Application Form", "Administrative Document"),
        ("Module 1", "1.3", "Product Information, if applicable", "Labelling Document"),
        ("Module 2", "2.3", "Quality Overall Summary, if applicable", "Summary Document"),
        ("Module 3", "Affected Quality Section", "Updated Quality Documentation", "CMC Document"),
        ("Module 3", "Supporting Data", "Comparative / Justification Data", "Supporting Document")
    ],

    "II": [
        ("Module 1", "1.0", "Cover Letter", "Administrative Document"),
        ("Module 1", "1.2", "Application Form", "Administrative Document"),
        ("Module 1", "1.3", "Product Information", "Labelling Document"),
        ("Module 2", "2.3", "Quality Overall Summary", "Summary Document"),
        ("Module 3", "3.2.S", "Drug Substance Documentation, if applicable", "CMC Document"),
        ("Module 3", "3.2.P", "Drug Product Documentation, if applicable", "CMC Document"),
        ("Module 5", "5.3", "Clinical Study Data, if applicable", "Clinical Document")
    ],

    "Extension": [
        ("Module 1", "1.0", "Cover Letter", "Administrative Document"),
        ("Module 1", "1.2", "Application Form", "Administrative Document"),
        ("Module 1", "1.3", "Product Information", "Labelling Document"),
        ("Module 2", "2.3", "Quality Overall Summary", "Summary Document"),
        ("Module 2", "2.5", "Clinical Overview, if applicable", "Clinical Document"),
        ("Module 2", "2.7", "Clinical Summary, if applicable", "Clinical Document"),
        ("Module 3", "3.2.S", "Drug Substance Documentation", "CMC Document"),
        ("Module 3", "3.2.P", "Drug Product Documentation", "CMC Document"),
        ("Module 5", "5.3", "Clinical Data, if applicable", "Clinical Document"),
        ("Annex", "Annex A", "Product Presentation", "Annex Document")
    ]
}

# Owner mapping
owner_mapping = {
    "Administrative Document": "Regulatory Affairs",
    "Labelling Document": "Labelling Team",
    "Summary Document": "CMC Regulatory Lead",
    "CMC Document": "CMC Team",
    "Clinical Document": "Clinical Team",
    "Supporting Document": "Regulatory Affairs",
    "Annex Document": "Regulatory Affairs"
}

# Function to assign content status based on submission status
def assign_content_status(submission_status):
    submission_status = str(submission_status).strip()

    if submission_status in ["Archived", "Implemented"]:
        return "Approved"
    elif submission_status == "Approved - Pending Implementation":
        return "Approved"
    elif submission_status == "Under Assessment":
        return "Published"
    elif submission_status == "In Preparation":
        return "In Review"
    elif submission_status == "Implementation Overdue":
        return "Approved"
    elif submission_status == "Not Started":
        return "Not Started"
    else:
        return "Planned"

# Function to assign readiness flag
def assign_readiness_flag(content_status):
    if content_status in ["Approved", "Published"]:
        return "Ready"
    elif content_status in ["In Review", "Draft"]:
        return "In Progress"
    else:
        return "Not Ready"

# Function to normalize variation category
def normalize_variation_category(variation_category):
    category = str(variation_category).strip()

    if category in ["Type IA", "IA"]:
        return "IA"
    elif category in ["Type IAIN", "IAIN"]:
        return "IAIN"
    elif category in ["Type IB", "IB"]:
        return "IB"
    elif category in ["Type II", "II", "II-S", "II-C", "II-U"]:
        return "II"
    elif category.lower() == "extension":
        return "Extension"
    else:
        return "IB"

content_plan_rows = []

for index, row in submissions.iterrows():

    submission_id = row.get("Submission_ID", f"SUB-{index+1:03d}")
    product_name = row.get("Product_Name", "Novalex")
    variation_category = row.get("Variation_Category", "")
    submission_title = row.get("Submission_Title", "")
    procedure = row.get("Procedure", "Centralised")
    health_authority = row.get("Health_Authority", "EMA")
    submission_status = row.get("Submission_Status", "")
    risk_level = row.get("Risk_Level", "Medium")
    planned_submission_date = row.get("Planned_Submission_Date", pd.NaT)
    actual_submission_date = row.get("Actual_Submission_Date", pd.NaT)

    template_key = normalize_variation_category(variation_category)
    template = ctd_templates.get(template_key, [])

    for item_number, item in enumerate(template, start=1):
        ctd_module, ctd_section, required_document, document_type = item

        content_status = assign_content_status(submission_status)
        readiness_flag = assign_readiness_flag(content_status)
        owner = owner_mapping.get(document_type, "Regulatory Affairs")

        # Planned due date is 10 days before planned submission date
        if pd.notna(planned_submission_date):
            planned_due_date = planned_submission_date - timedelta(days=10)
        else:
            planned_due_date = pd.NaT

        # Actual completion date based on content status
        if content_status == "Approved":
            if pd.notna(actual_submission_date):
                actual_completion_date = actual_submission_date - timedelta(days=3)
            elif pd.notna(planned_submission_date):
                actual_completion_date = planned_submission_date - timedelta(days=3)
            else:
                actual_completion_date = pd.NaT

        elif content_status == "Published":
            if pd.notna(actual_submission_date):
                actual_completion_date = actual_submission_date
            elif pd.notna(planned_submission_date):
                actual_completion_date = planned_submission_date
            else:
                actual_completion_date = pd.NaT

        else:
            actual_completion_date = pd.NaT

        content_plan_rows.append({
            "Content_Plan_ID": f"CP-{index+1:03d}-{item_number:02d}",
            "Submission_ID": submission_id,
            "Product_Name": product_name,
            "Variation_Category": variation_category,
            "Submission_Title": submission_title,
            "Procedure": procedure,
            "Health_Authority": health_authority,
            "CTD_Module": ctd_module,
            "CTD_Section": ctd_section,
            "Required_Document": required_document,
            "Document_Type": document_type,
            "Document_Owner": owner,
            "Planned_Due_Date": planned_due_date,
            "Actual_Completion_Date": actual_completion_date,
            "Content_Status": content_status,
            "Mandatory_or_Optional": "Mandatory",
            "Readiness_Flag": readiness_flag,
            "Risk_Level": risk_level,
            "Comments": ""
        })

content_plan = pd.DataFrame(content_plan_rows)

# Save output
output_file = "Novalex_Content_Plan_Tracker.xlsx"
content_plan.to_excel(output_file, index=False)

print("Content plan created successfully!")
print("Output file:", output_file)
print("Rows created:", len(content_plan))

display(content_plan.head(20))

content_plan[["Submission_ID", "Content_Status", "Planned_Due_Date", "Actual_Completion_Date"]].head(20)

from google.colab import files

files.download("Novalex_Content_Plan_Tracker.xlsx")

content_plan = pd.DataFrame(content_plan_rows)

output_file = "Novalex_Content_Plan_Tracker.xlsx"
content_plan.to_excel(output_file, index=False)

print("Content plan created successfully!")
print("Output file:", output_file)
print("Rows created:", len(content_plan))

display(content_plan.head(20))

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
files.download("Novalex_Content_Plan_Tracker.xlsx")

import os

os.listdir()

import pandas as pd
from datetime import timedelta

content_plan_file = "Novalex_Content_Plan_Tracker.xlsx"

content_plan = pd.read_excel(content_plan_file)

print("Content Plan shape:", content_plan.shape)
display(content_plan.head())

content_plan.columns = content_plan.columns.str.strip().str.replace(" ", "_")

print(content_plan.columns.tolist())

content_plan["Planned_Due_Date"] = pd.to_datetime(content_plan["Planned_Due_Date"], errors="coerce")
content_plan["Actual_Completion_Date"] = pd.to_datetime(content_plan["Actual_Completion_Date"], errors="coerce")

print(content_plan[["Planned_Due_Date", "Actual_Completion_Date"]].head())

def map_document_status(content_status):
    content_status = str(content_status).strip()

    if content_status == "Not Started":
        return "Not Started"
    elif content_status == "Planned":
        return "Draft"
    elif content_status == "In Review":
        return "In Review"
    elif content_status == "Approved":
        return "Approved"
    elif content_status == "Published":
        return "Published"
    else:
        return "Draft"


def assign_version(document_status):
    if document_status == "Not Started":
        return ""
    elif document_status == "Draft":
        return "v0.1"
    elif document_status == "In Review":
        return "v0.2"
    elif document_status == "Approved":
        return "v1.0"
    elif document_status == "Published":
        return "v1.0 Published"
    else:
        return "v0.1"


def assign_final_or_draft(document_status):
    if document_status in ["Approved", "Published"]:
        return "Final"
    elif document_status == "Not Started":
        return "Not Created"
    else:
        return "Draft"


def assign_overdue_flag(document_status, planned_due_date):
    today = pd.Timestamp.today().normalize()

    if document_status in ["Approved", "Published"]:
        return "No"
    elif pd.notna(planned_due_date) and planned_due_date < today:
        return "Yes"
    else:
        return "No"


def assign_author(document_type, owner):
    document_type = str(document_type).strip()
    owner = str(owner).strip()

    if document_type == "Administrative Document":
        return "Regulatory Affairs Associate"
    elif document_type == "Labelling Document":
        return "Labelling Specialist"
    elif document_type == "Summary Document":
        return "CMC Regulatory Lead"
    elif document_type == "CMC Document":
        return "CMC Documentation Specialist"
    elif document_type == "Clinical Document":
        return "Clinical Regulatory Writer"
    elif document_type == "Supporting Document":
        return "Regulatory Affairs Associate"
    elif document_type == "Annex Document":
        return "Regulatory Affairs Associate"
    else:
        return owner


def assign_reviewer(document_type):
    document_type = str(document_type).strip()

    if document_type == "Administrative Document":
        return "Regulatory Affairs Manager"
    elif document_type == "Labelling Document":
        return "Labelling Lead"
    elif document_type == "Summary Document":
        return "CMC Review Lead"
    elif document_type == "CMC Document":
        return "Quality / CMC Reviewer"
    elif document_type == "Clinical Document":
        return "Clinical Reviewer"
    elif document_type == "Supporting Document":
        return "Regulatory Affairs Manager"
    elif document_type == "Annex Document":
        return "Regulatory Affairs Manager"
    else:
        return "Regulatory Reviewer"


def assign_approver(document_type):
    document_type = str(document_type).strip()

    if document_type in ["CMC Document", "Summary Document"]:
        return "Head of CMC Regulatory"
    elif document_type == "Clinical Document":
        return "Clinical Regulatory Lead"
    elif document_type == "Labelling Document":
        return "Head of Labelling"
    else:
        return "Regulatory Affairs Lead"

document_rows = []

for index, row in content_plan.iterrows():

    content_plan_id = row.get("Content_Plan_ID", f"CP-{index+1:03d}")
    submission_id = row.get("Submission_ID", "")
    product_name = row.get("Product_Name", "Novalex")
    variation_category = row.get("Variation_Category", "")
    ctd_module = row.get("CTD_Module", "")
    ctd_section = row.get("CTD_Section", "")
    required_document = row.get("Required_Document", "")
    document_type = row.get("Document_Type", "")
    document_owner = row.get("Document_Owner", "")
    planned_due_date = row.get("Planned_Due_Date", pd.NaT)
    actual_completion_date = row.get("Actual_Completion_Date", pd.NaT)
    content_status = row.get("Content_Status", "")
    risk_level = row.get("Risk_Level", "Medium")

    document_status = map_document_status(content_status)
    version = assign_version(document_status)
    final_or_draft = assign_final_or_draft(document_status)
    overdue_flag = assign_overdue_flag(document_status, planned_due_date)

    author = assign_author(document_type, document_owner)
    reviewer = assign_reviewer(document_type)
    approver = assign_approver(document_type)

    # Date logic
    if document_status == "Not Started":
        draft_start_date = pd.NaT
        review_start_date = pd.NaT
        approval_date = pd.NaT

    elif document_status == "Draft":
        if pd.notna(planned_due_date):
            draft_start_date = planned_due_date - timedelta(days=10)
        else:
            draft_start_date = pd.NaT
        review_start_date = pd.NaT
        approval_date = pd.NaT

    elif document_status == "In Review":
        if pd.notna(planned_due_date):
            draft_start_date = planned_due_date - timedelta(days=15)
            review_start_date = planned_due_date - timedelta(days=5)
        else:
            draft_start_date = pd.NaT
            review_start_date = pd.NaT
        approval_date = pd.NaT

    elif document_status in ["Approved", "Published"]:
        if pd.notna(planned_due_date):
            draft_start_date = planned_due_date - timedelta(days=20)
            review_start_date = planned_due_date - timedelta(days=10)
        else:
            draft_start_date = pd.NaT
            review_start_date = pd.NaT

        if pd.notna(actual_completion_date):
            approval_date = actual_completion_date
        elif pd.notna(planned_due_date):
            approval_date = planned_due_date
        else:
            approval_date = pd.NaT

    else:
        draft_start_date = pd.NaT
        review_start_date = pd.NaT
        approval_date = pd.NaT

    # Days in review
    if pd.notna(review_start_date) and pd.notna(approval_date):
        days_in_review = (approval_date - review_start_date).days
    elif pd.notna(review_start_date):
        days_in_review = (pd.Timestamp.today().normalize() - review_start_date).days
    else:
        days_in_review = ""

    document_rows.append({
        "Document_ID": f"DOC-{index+1:05d}",
        "Content_Plan_ID": content_plan_id,
        "Submission_ID": submission_id,
        "Product_Name": product_name,
        "Variation_Category": variation_category,
        "CTD_Module": ctd_module,
        "CTD_Section": ctd_section,
        "Document_Name": required_document,
        "Document_Type": document_type,
        "Version": version,
        "Author": author,
        "Reviewer": reviewer,
        "Approver": approver,
        "Document_Status": document_status,
        "Draft_Start_Date": draft_start_date,
        "Review_Start_Date": review_start_date,
        "Approval_Date": approval_date,
        "Days_In_Review": days_in_review,
        "Overdue_Flag": overdue_flag,
        "Final_or_Draft": final_or_draft,
        "Risk_Level": risk_level,
        "Comments": ""
    })

document_lifecycle = pd.DataFrame(document_rows)

output_file = "Novalex_Document_Lifecycle_Tracker.xlsx"
document_lifecycle.to_excel(output_file, index=False)

print("Document Lifecycle Tracker created successfully!")
print("Output file:", output_file)
print("Rows created:", len(document_lifecycle))

display(document_lifecycle.head(20))

document_lifecycle["Document_Status"].value_counts()

display(document_lifecycle.head(30))

from google.colab import files

files.download("Novalex_Document_Lifecycle_Tracker.xlsx")

import os

os.listdir()

import pandas as pd
from datetime import timedelta

submission_file = "Novalex Submission Tracker.xlsx"
document_file = "Novalex_Document_Lifecycle_Tracker.xlsx"

submissions = pd.read_excel(submission_file)
documents = pd.read_excel(document_file)

print("Submission Tracker shape:", submissions.shape)
print("Document Lifecycle Tracker shape:", documents.shape)

display(submissions.head())
display(documents.head())

submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
documents.columns = documents.columns.str.strip().str.replace(" ", "_")

print("Submission columns:")
print(submissions.columns.tolist())

print("\nDocument columns:")
print(documents.columns.tolist())

date_columns_submissions = [
    "Planned_Submission_Date",
    "Actual_Submission_Date",
    "Approval_Decision_Date",
    "Approval_Date"
]

for col in date_columns_submissions:
    if col in submissions.columns:
        submissions[col] = pd.to_datetime(submissions[col], errors="coerce")

if "Approval_Date" in documents.columns:
    documents["Approval_Date"] = pd.to_datetime(documents["Approval_Date"], errors="coerce")

def get_submission_id(row, index):
    possible_cols = ["Submission_ID", "Unique_Submission_ID", "Submission_Id"]
    for col in possible_cols:
        if col in row.index and pd.notna(row.get(col)):
            return row.get(col)
    return f"SUB-{index+1:03d}"


def normalize_submission_status(status):
    return str(status).strip()


def assign_sequence_number(index):
    return f"{index+1:04d}"


def assign_submission_format(variation_category):
    return "eCTD"


def assign_lifecycle_operation(variation_category, submission_status):
    variation_category = str(variation_category).strip()
    submission_status = str(submission_status).strip()

    if variation_category in ["IA", "Type IA", "IAIN", "Type IAIN"]:
        return "Replace"
    elif variation_category in ["IB", "Type IB"]:
        return "Replace"
    elif variation_category in ["II", "Type II", "II-S", "II-C", "II-U"]:
        return "Replace"
    elif variation_category.lower() == "extension":
        return "New"
    elif submission_status == "Not Started":
        return "Not Assigned"
    else:
        return "Replace"


def assign_publishing_status(submission_status, readiness_percent):
    submission_status = normalize_submission_status(submission_status)

    if submission_status == "Not Started":
        return "Not Started"
    elif submission_status == "In Preparation":
        if readiness_percent >= 80:
            return "Publishing In Progress"
        else:
            return "Not Started"
    elif submission_status == "Under Assessment":
        return "Submitted to Health Authority"
    elif submission_status in ["Approved - Pending Implementation", "Implementation Overdue", "Implemented", "Archived"]:
        return "Completed"
    else:
        return "QC Review"


def assign_validation_status(publishing_status, readiness_percent):
    if publishing_status == "Not Started":
        return "Not Started"
    elif publishing_status == "Publishing In Progress":
        return "Pending"
    elif publishing_status == "QC Review":
        return "Pending"
    elif publishing_status in ["Submitted to Health Authority", "Completed"]:
        if readiness_percent >= 95:
            return "Passed"
        else:
            return "Passed with Minor Comments"
    else:
        return "Pending"


def assign_validation_errors(validation_status, readiness_percent):
    if validation_status == "Not Started":
        return 0
    elif validation_status == "Pending":
        return ""
    elif validation_status == "Passed":
        return 0
    elif validation_status == "Passed with Minor Comments":
        return 1
    else:
        return ""


def assign_final_package_status(publishing_status, validation_status):
    if publishing_status == "Not Started":
        return "Not Created"
    elif validation_status in ["Passed", "Passed with Minor Comments"]:
        return "Final Package Available"
    elif validation_status == "Pending":
        return "Package Under Preparation"
    else:
        return "Package Not Ready"


def assign_gateway_status(submission_status):
    submission_status = normalize_submission_status(submission_status)

    if submission_status in ["Under Assessment", "Approved - Pending Implementation", "Implementation Overdue", "Implemented", "Archived"]:
        return "Submitted"
    elif submission_status == "In Preparation":
        return "Pending"
    elif submission_status == "Not Started":
        return "Not Submitted"
    else:
        return "Pending"


def assign_acknowledgement_received(gateway_status):
    if gateway_status == "Submitted":
        return "Yes"
    else:
        return "No"


def assign_publisher():
    return "Regulatory Publishing Specialist"


def assign_qc_reviewer():
    return "Publishing QC Reviewer"

ready_statuses = ["Approved", "Published"]

doc_summary = documents.groupby("Submission_ID").agg(
    Total_Documents=("Document_ID", "count"),
    Ready_Documents=("Document_Status", lambda x: x.isin(ready_statuses).sum()),
    Pending_Documents=("Document_Status", lambda x: (~x.isin(ready_statuses)).sum())
).reset_index()

doc_summary["Readiness_Percent"] = (
    doc_summary["Ready_Documents"] / doc_summary["Total_Documents"] * 100
).round(2)

display(doc_summary.head())

submissions_with_docs = submissions.merge(
    doc_summary,
    on="Submission_ID",
    how="left"
)

submissions_with_docs["Total_Documents"] = submissions_with_docs["Total_Documents"].fillna(0).astype(int)
submissions_with_docs["Ready_Documents"] = submissions_with_docs["Ready_Documents"].fillna(0).astype(int)
submissions_with_docs["Pending_Documents"] = submissions_with_docs["Pending_Documents"].fillna(0).astype(int)
submissions_with_docs["Readiness_Percent"] = submissions_with_docs["Readiness_Percent"].fillna(0)

display(submissions_with_docs.head())

print("Submission columns:")
print(submissions.columns.tolist())

print("\nDocument summary columns:")
print(doc_summary.columns.tolist())

# Rename possible submission ID columns to Submission_ID

possible_submission_id_columns = [
    "Submission_ID",
    "Submission_Id",
    "SubmissionID",
    "Submission_ID_",
    "Unique_Submission_ID",
    "Unique_Submission_Id",
    "Submission_Number",
    "Submission_No",
    "Submission_Code"
]

found_column = None

for col in possible_submission_id_columns:
    if col in submissions.columns:
        found_column = col
        break

if found_column:
    submissions = submissions.rename(columns={found_column: "Submission_ID"})
    print(f"Renamed '{found_column}' to 'Submission_ID'")
else:
    print("No submission ID column found. Available columns are:")
    print(submissions.columns.tolist())

possible_document_submission_id_columns = [
    "Submission_ID",
    "Submission_Id",
    "SubmissionID",
    "Submission_ID_",
    "Unique_Submission_ID",
    "Unique_Submission_Id",
    "Submission_Number",
    "Submission_No",
    "Submission_Code"
]

found_doc_column = None

for col in possible_document_submission_id_columns:
    if col in documents.columns:
        found_doc_column = col
        break

if found_doc_column:
    documents = documents.rename(columns={found_doc_column: "Submission_ID"})
    print(f"Document tracker column '{found_doc_column}' is now 'Submission_ID'")
else:
    print("No submission ID column found in document tracker. Available columns are:")
    print(documents.columns.tolist())

ready_statuses = ["Approved", "Published"]

doc_summary = documents.groupby("Submission_ID").agg(
    Total_Documents=("Document_ID", "count"),
    Ready_Documents=("Document_Status", lambda x: x.isin(ready_statuses).sum()),
    Pending_Documents=("Document_Status", lambda x: (~x.isin(ready_statuses)).sum())
).reset_index()

doc_summary["Readiness_Percent"] = (
    doc_summary["Ready_Documents"] / doc_summary["Total_Documents"] * 100
).round(2)

display(doc_summary.head())

submissions_with_docs = submissions.merge(
    doc_summary,
    on="Submission_ID",
    how="left"
)

submissions_with_docs["Total_Documents"] = submissions_with_docs["Total_Documents"].fillna(0).astype(int)
submissions_with_docs["Ready_Documents"] = submissions_with_docs["Ready_Documents"].fillna(0).astype(int)
submissions_with_docs["Pending_Documents"] = submissions_with_docs["Pending_Documents"].fillna(0).astype(int)
submissions_with_docs["Readiness_Percent"] = submissions_with_docs["Readiness_Percent"].fillna(0)

display(submissions_with_docs.head())

publishing_rows = []

for index, row in submissions_with_docs.iterrows():

    submission_id = get_submission_id(row, index)
    product_name = row.get("Product_Name", "Novalex")
    variation_category = row.get("Variation_Category", row.get("Submission_Category", ""))
    submission_title = row.get("Submission_Title", "")
    submission_status = row.get("Submission_Status", "")
    planned_submission_date = row.get("Planned_Submission_Date", pd.NaT)
    actual_submission_date = row.get("Actual_Submission_Date", pd.NaT)

    total_documents = row.get("Total_Documents", 0)
    ready_documents = row.get("Ready_Documents", 0)
    pending_documents = row.get("Pending_Documents", 0)
    readiness_percent = row.get("Readiness_Percent", 0)

    sequence_number = assign_sequence_number(index)
    submission_format = assign_submission_format(variation_category)
    lifecycle_operation = assign_lifecycle_operation(variation_category, submission_status)

    publishing_status = assign_publishing_status(submission_status, readiness_percent)
    validation_status = assign_validation_status(publishing_status, readiness_percent)
    validation_errors = assign_validation_errors(validation_status, readiness_percent)

    final_package_status = assign_final_package_status(publishing_status, validation_status)
    gateway_submission_status = assign_gateway_status(submission_status)
    acknowledgement_received = assign_acknowledgement_received(gateway_submission_status)

    publisher = assign_publisher()
    qc_reviewer = assign_qc_reviewer()

    # Publish start and completion date logic
    if publishing_status == "Not Started":
        publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    elif publishing_status == "Publishing In Progress":
        if pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=7)
        else:
            publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    elif publishing_status == "QC Review":
        if pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=10)
            publish_complete_date = pd.NaT
        else:
            publish_start_date = pd.NaT
            publish_complete_date = pd.NaT

    elif publishing_status in ["Submitted to Health Authority", "Completed"]:
        if pd.notna(actual_submission_date):
            publish_start_date = actual_submission_date - timedelta(days=7)
            publish_complete_date = actual_submission_date - timedelta(days=1)
        elif pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=7)
            publish_complete_date = planned_submission_date - timedelta(days=1)
        else:
            publish_start_date = pd.NaT
            publish_complete_date = pd.NaT

    else:
        publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    # Acknowledgement date logic
    if acknowledgement_received == "Yes":
        if pd.notna(actual_submission_date):
            acknowledgement_date = actual_submission_date + timedelta(days=2)
        elif pd.notna(planned_submission_date):
            acknowledgement_date = planned_submission_date + timedelta(days=2)
        else:
            acknowledgement_date = pd.NaT
    else:
        acknowledgement_date = pd.NaT

    publishing_rows.append({
        "Publishing_ID": f"PUB-{index+1:04d}",
        "Submission_ID": submission_id,
        "Product_Name": product_name,
        "Variation_Category": variation_category,
        "Submission_Title": submission_title,
        "Submission_Status": submission_status,
        "Sequence_Number": sequence_number,
        "Submission_Format": submission_format,
        "Lifecycle_Operation": lifecycle_operation,
        "Total_Documents": total_documents,
        "Ready_Documents": ready_documents,
        "Pending_Documents": pending_documents,
        "Readiness_Percent": readiness_percent,
        "Publishing_Status": publishing_status,
        "Validation_Status": validation_status,
        "Validation_Errors": validation_errors,
        "Publish_Start_Date": publish_start_date,
        "Publish_Complete_Date": publish_complete_date,
        "Publisher": publisher,
        "QC_Reviewer": qc_reviewer,
        "Final_Package_Status": final_package_status,
        "Gateway_Submission_Status": gateway_submission_status,
        "Acknowledgement_Received": acknowledgement_received,
        "Acknowledgement_Date": acknowledgement_date,
        "Comments": ""
    })

publishing_tracker = pd.DataFrame(publishing_rows)

output_file = "Novalex_Publishing_Tracker.xlsx"
publishing_tracker.to_excel(output_file, index=False)

print("Publishing Tracker created successfully!")
print("Output file:", output_file)
print("Rows created:", len(publishing_tracker))

display(publishing_tracker.head(20))

publishing_tracker["Publishing_Status"].value_counts()

from google.colab import files

files.download("Novalex_Publishing_Tracker.xlsx")

print("Submission Tracker IDs:")
print(submissions["Submission_ID"].head(10).tolist())

print("\nDocument Lifecycle Tracker IDs:")
print(documents["Submission_ID"].head(10).tolist())

submission_ids = set(submissions["Submission_ID"].astype(str).str.strip())
document_ids = set(documents["Submission_ID"].astype(str).str.strip())

matching_ids = submission_ids.intersection(document_ids)

print("Submission Tracker unique IDs:", len(submission_ids))
print("Document Tracker unique IDs:", len(document_ids))
print("Matching IDs:", len(matching_ids))

print("\nExample matching IDs:")
print(list(matching_ids)[:10])

print("\nSubmission IDs not found in document tracker:")
print(list(submission_ids - document_ids)[:10])

print("\nDocument IDs not found in submission tracker:")
print(list(document_ids - submission_ids)[:10])

print(submissions.columns.tolist())

print("Submission Tracker IDs:")
print(submissions["Submission_ID"].head(10).tolist())

print("\nDocument Lifecycle Tracker IDs:")
print(documents["Submission_ID"].head(10).tolist())

submission_file = "Novalex Submission Tracker.xlsx"
document_file = "Novalex_Document_Lifecycle_Tracker.xlsx"

submissions = pd.read_excel(submission_file)
documents = pd.read_excel(document_file)

submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
documents.columns = documents.columns.str.strip().str.replace(" ", "_")

# Fix Submission_ID format so both files can match

# Clean both Submission_ID columns
submissions["Submission_ID"] = submissions["Submission_ID"].astype(str).str.strip()
documents["Submission_ID"] = documents["Submission_ID"].astype(str).str.strip()

# Convert document IDs from SUB-001 to NVX-SUB-001
documents["Submission_ID"] = documents["Submission_ID"].apply(
    lambda x: "NVX-" + x if x.startswith("SUB-") else x
)

# Check result
print("Submission Tracker IDs:")
print(submissions["Submission_ID"].head(10).tolist())

print("\nCorrected Document Lifecycle Tracker IDs:")
print(documents["Submission_ID"].head(10).tolist())

print("Submission Tracker columns:")
print(submissions.columns.tolist())

print("\nDocument Lifecycle Tracker columns:")
print(documents.columns.tolist())

# Clean column names again
submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
documents.columns = documents.columns.str.strip().str.replace(" ", "_")

# Print columns so we can see them
print("Submission Tracker columns:")
print(submissions.columns.tolist())

print("\nDocument Lifecycle Tracker columns:")
print(documents.columns.tolist())

# Possible names for submission ID columns
possible_id_columns = [
    "Submission_ID",
    "Submission_Id",
    "SubmissionID",
    "Unique_Submission_ID",
    "Unique_Submission_Id",
    "Unique_SubmissionID",
    "Submission_Number",
    "Submission_No",
    "Submission_Code",
    "ID"
]

# Find submission ID column in submission tracker
submission_id_col = None
for col in possible_id_columns:
    if col in submissions.columns:
        submission_id_col = col
        break

# Find submission ID column in document lifecycle tracker
document_id_col = None
for col in possible_id_columns:
    if col in documents.columns:
        document_id_col = col
        break

print("\nDetected submission tracker ID column:", submission_id_col)
print("Detected document tracker ID column:", document_id_col)

# Stop if not found
if submission_id_col is None:
    raise ValueError("Could not find submission ID column in Submission Tracker. Check printed column names above.")

if document_id_col is None:
    raise ValueError("Could not find submission ID column in Document Lifecycle Tracker. Check printed column names above.")

# Rename both to Submission_ID
submissions = submissions.rename(columns={submission_id_col: "Submission_ID"})
documents = documents.rename(columns={document_id_col: "Submission_ID"})

# Clean ID values
submissions["Submission_ID"] = submissions["Submission_ID"].astype(str).str.strip()
documents["Submission_ID"] = documents["Submission_ID"].astype(str).str.strip()

# Convert document IDs from SUB-001 to NVX-SUB-001
documents["Submission_ID"] = documents["Submission_ID"].apply(
    lambda x: "NVX-" + x if x.startswith("SUB-") else x
)

print("\nSubmission Tracker IDs:")
print(submissions["Submission_ID"].head(10).tolist())

print("\nCorrected Document Lifecycle Tracker IDs:")
print(documents["Submission_ID"].head(10).tolist())

submission_ids = set(submissions["Submission_ID"])
document_ids = set(documents["Submission_ID"])

matching_ids = submission_ids.intersection(document_ids)

print("Submission Tracker unique IDs:", len(submission_ids))
print("Document Tracker unique IDs:", len(document_ids))
print("Matching IDs:", len(matching_ids))
print("Example matching IDs:", list(matching_ids)[:10])

ready_statuses = ["Approved", "Published"]

doc_summary = documents.groupby("Submission_ID").agg(
    Total_Documents=("Document_ID", "count"),
    Ready_Documents=("Document_Status", lambda x: x.isin(ready_statuses).sum()),
    Pending_Documents=("Document_Status", lambda x: (~x.isin(ready_statuses)).sum())
).reset_index()

doc_summary["Readiness_Percent"] = (
    doc_summary["Ready_Documents"] / doc_summary["Total_Documents"] * 100
).round(2)

display(doc_summary.head())

submissions_with_docs = submissions.merge(
    doc_summary,
    on="Submission_ID",
    how="left"
)

submissions_with_docs["Total_Documents"] = submissions_with_docs["Total_Documents"].fillna(0).astype(int)
submissions_with_docs["Ready_Documents"] = submissions_with_docs["Ready_Documents"].fillna(0).astype(int)
submissions_with_docs["Pending_Documents"] = submissions_with_docs["Pending_Documents"].fillna(0).astype(int)
submissions_with_docs["Readiness_Percent"] = submissions_with_docs["Readiness_Percent"].fillna(0)

display(submissions_with_docs[[
    "Submission_ID",
    "Total_Documents",
    "Ready_Documents",
    "Pending_Documents",
    "Readiness_Percent"
]].head(20))

publishing_rows = []

for index, row in submissions_with_docs.iterrows():

    submission_id = get_submission_id(row, index)
    product_name = row.get("Product_Name", "Novalex")
    variation_category = row.get("Variation_Category", row.get("Submission_Category", ""))
    submission_title = row.get("Submission_Title", "")
    submission_status = row.get("Submission_Status", "")
    planned_submission_date = row.get("Planned_Submission_Date", pd.NaT)
    actual_submission_date = row.get("Actual_Submission_Date", pd.NaT)

    total_documents = row.get("Total_Documents", 0)
    ready_documents = row.get("Ready_Documents", 0)
    pending_documents = row.get("Pending_Documents", 0)
    readiness_percent = row.get("Readiness_Percent", 0)

    sequence_number = assign_sequence_number(index)
    submission_format = assign_submission_format(variation_category)
    lifecycle_operation = assign_lifecycle_operation(variation_category, submission_status)

    publishing_status = assign_publishing_status(submission_status, readiness_percent)
    validation_status = assign_validation_status(publishing_status, readiness_percent)
    validation_errors = assign_validation_errors(validation_status, readiness_percent)

    final_package_status = assign_final_package_status(publishing_status, validation_status)
    gateway_submission_status = assign_gateway_status(submission_status)
    acknowledgement_received = assign_acknowledgement_received(gateway_submission_status)

    publisher = assign_publisher()
    qc_reviewer = assign_qc_reviewer()

    # Publish start and completion date logic
    if publishing_status == "Not Started":
        publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    elif publishing_status == "Publishing In Progress":
        if pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=7)
        else:
            publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    elif publishing_status == "QC Review":
        if pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=10)
            publish_complete_date = pd.NaT
        else:
            publish_start_date = pd.NaT
            publish_complete_date = pd.NaT

    elif publishing_status in ["Submitted to Health Authority", "Completed"]:
        if pd.notna(actual_submission_date):
            publish_start_date = actual_submission_date - timedelta(days=7)
            publish_complete_date = actual_submission_date - timedelta(days=1)
        elif pd.notna(planned_submission_date):
            publish_start_date = planned_submission_date - timedelta(days=7)
            publish_complete_date = planned_submission_date - timedelta(days=1)
        else:
            publish_start_date = pd.NaT
            publish_complete_date = pd.NaT

    else:
        publish_start_date = pd.NaT
        publish_complete_date = pd.NaT

    # Acknowledgement date logic
    if acknowledgement_received == "Yes":
        if pd.notna(actual_submission_date):
            acknowledgement_date = actual_submission_date + timedelta(days=2)
        elif pd.notna(planned_submission_date):
            acknowledgement_date = planned_submission_date + timedelta(days=2)
        else:
            acknowledgement_date = pd.NaT
    else:
        acknowledgement_date = pd.NaT

    publishing_rows.append({
        "Publishing_ID": f"PUB-{index+1:04d}",
        "Submission_ID": submission_id,
        "Product_Name": product_name,
        "Variation_Category": variation_category,
        "Submission_Title": submission_title,
        "Submission_Status": submission_status,
        "Sequence_Number": sequence_number,
        "Submission_Format": submission_format,
        "Lifecycle_Operation": lifecycle_operation,
        "Total_Documents": total_documents,
        "Ready_Documents": ready_documents,
        "Pending_Documents": pending_documents,
        "Readiness_Percent": readiness_percent,
        "Publishing_Status": publishing_status,
        "Validation_Status": validation_status,
        "Validation_Errors": validation_errors,
        "Publish_Start_Date": publish_start_date,
        "Publish_Complete_Date": publish_complete_date,
        "Publisher": publisher,
        "QC_Reviewer": qc_reviewer,
        "Final_Package_Status": final_package_status,
        "Gateway_Submission_Status": gateway_submission_status,
        "Acknowledgement_Received": acknowledgement_received,
        "Acknowledgement_Date": acknowledgement_date,
        "Comments": ""
    })

publishing_tracker = pd.DataFrame(publishing_rows)

output_file = "Novalex_Publishing_Tracker.xlsx"
publishing_tracker.to_excel(output_file, index=False)

print("Publishing Tracker created successfully!")
print("Output file:", output_file)
print("Rows created:", len(publishing_tracker))

display(publishing_tracker.head(20))

publishing_tracker["Publishing_Status"].value_counts()

publishing_tracker["Validation_Status"].value_counts()

from google.colab import files

files.download("Novalex_Publishing_Tracker.xlsx")

import os

os.listdir()

import pandas as pd
from datetime import timedelta

submission_file = "Novalex Submission Tracker.xlsx"
publishing_file = "Novalex_Publishing_Tracker.xlsx"
query_file = "Novalex Agency Query Tracker.xlsx"

submissions = pd.read_excel(submission_file)
publishing = pd.read_excel(publishing_file)
queries = pd.read_excel(query_file)

print("Submission Tracker shape:", submissions.shape)
print("Publishing Tracker shape:", publishing.shape)
print("Agency Query Tracker shape:", queries.shape)

display(submissions.head())
display(publishing.head())
display(queries.head())

submissions.columns = submissions.columns.str.strip().str.replace(" ", "_")
publishing.columns = publishing.columns.str.strip().str.replace(" ", "_")
queries.columns = queries.columns.str.strip().str.replace(" ", "_")

print("Submission columns:")
print(submissions.columns.tolist())

print("\nPublishing columns:")
print(publishing.columns.tolist())

print("\nQuery columns:")
print(queries.columns.tolist())

# Possible ID column names
possible_id_columns = [
    "Submission_ID",
    "Submission_Id",
    "SubmissionID",
    "Unique_Submission_ID",
    "Unique_Submission_Id",
    "Unique_SubmissionID",
    "Submission_Number",
    "Submission_No",
    "Submission_Code",
    "ID"
]

def find_id_column(df):
    for col in possible_id_columns:
        if col in df.columns:
            return col
    return None

submission_id_col = find_id_column(submissions)
publishing_id_col = find_id_column(publishing)
query_id_col = find_id_column(queries)

print("Submission ID column:", submission_id_col)
print("Publishing ID column:", publishing_id_col)
print("Query ID column:", query_id_col)

if submission_id_col is None:
    raise ValueError("Could not find Submission_ID column in submissions file.")

if publishing_id_col is None:
    raise ValueError("Could not find Submission_ID column in publishing file.")

# Rename to common name
submissions = submissions.rename(columns={submission_id_col: "Submission_ID"})
publishing = publishing.rename(columns={publishing_id_col: "Submission_ID"})

if query_id_col is not None:
    queries = queries.rename(columns={query_id_col: "Submission_ID"})

# Clean ID values
submissions["Submission_ID"] = submissions["Submission_ID"].astype(str).str.strip()
publishing["Submission_ID"] = publishing["Submission_ID"].astype(str).str.strip()

if "Submission_ID" in queries.columns:
    queries["Submission_ID"] = queries["Submission_ID"].astype(str).str.strip()

# Convert SUB-001 to NVX-SUB-001 if needed
publishing["Submission_ID"] = publishing["Submission_ID"].apply(
    lambda x: "NVX-" + x if x.startswith("SUB-") else x
)

if "Submission_ID" in queries.columns:
    queries["Submission_ID"] = queries["Submission_ID"].apply(
        lambda x: "NVX-" + x if x.startswith("SUB-") else x
    )

print("\nSubmission Tracker IDs:")
print(submissions["Submission_ID"].head(10).tolist())

print("\nPublishing Tracker IDs:")
print(publishing["Submission_ID"].head(10).tolist())

if "Submission_ID" in queries.columns:
    print("\nAgency Query Tracker IDs:")
    print(queries["Submission_ID"].head(10).tolist())

date_columns_submissions = [
    "Planned_Submission_Date",
    "Actual_Submission_Date",
    "Approval_Decision_Date",
    "Approval_Date",
    "Target_Implementation_Date",
    "Actual_Implementation_Date"
]

for col in date_columns_submissions:
    if col in submissions.columns:
        submissions[col] = pd.to_datetime(submissions[col], errors="coerce")

date_columns_publishing = [
    "Publish_Start_Date",
    "Publish_Complete_Date",
    "Acknowledgement_Date"
]

for col in date_columns_publishing:
    if col in publishing.columns:
        publishing[col] = pd.to_datetime(publishing[col], errors="coerce")

date_columns_queries = [
    "Query_Received_Date",
    "Response_Due_Date",
    "Response_Submitted_Date",
    "Agency_Final_Response_Date"
]

for col in date_columns_queries:
    if col in queries.columns:
        queries[col] = pd.to_datetime(queries[col], errors="coerce")

if "Submission_ID" in queries.columns:
    query_summary = queries.groupby("Submission_ID").agg(
        Total_Agency_Queries=("Submission_ID", "count")
    ).reset_index()
else:
    query_summary = pd.DataFrame(columns=["Submission_ID", "Total_Agency_Queries"])

display(query_summary.head())

archive_base = publishing.merge(
    submissions,
    on="Submission_ID",
    how="left",
    suffixes=("_Publishing", "_Submission")
)

archive_base = archive_base.merge(
    query_summary,
    on="Submission_ID",
    how="left"
)

archive_base["Total_Agency_Queries"] = archive_base["Total_Agency_Queries"].fillna(0).astype(int)

display(archive_base.head())

def get_first_available(row, columns, default=""):
    for col in columns:
        if col in row.index and pd.notna(row.get(col)):
            return row.get(col)
    return default


def assign_archive_status(submission_status, publishing_status, final_package_status):
    submission_status = str(submission_status).strip()
    publishing_status = str(publishing_status).strip()
    final_package_status = str(final_package_status).strip()

    if submission_status == "Archived":
        return "Archived"
    elif submission_status in ["Implemented"]:
        return "Archived"
    elif submission_status in ["Approved - Pending Implementation", "Implementation Overdue"]:
        return "Ready for Archive"
    elif submission_status == "Under Assessment":
        return "Not Ready - Under Assessment"
    elif submission_status == "In Preparation":
        return "Not Ready - In Preparation"
    elif submission_status == "Not Started":
        return "Not Ready - Not Started"
    elif publishing_status == "Completed" and final_package_status == "Final Package Available":
        return "Ready for Archive"
    else:
        return "Not Ready"


def assign_archive_date(archive_status, publish_complete_date, actual_submission_date, approval_date):
    if archive_status == "Archived":
        if pd.notna(approval_date):
            return approval_date + timedelta(days=5)
        elif pd.notna(publish_complete_date):
            return publish_complete_date + timedelta(days=10)
        elif pd.notna(actual_submission_date):
            return actual_submission_date + timedelta(days=15)
        else:
            return pd.NaT

    elif archive_status == "Ready for Archive":
        if pd.notna(approval_date):
            return approval_date + timedelta(days=7)
        elif pd.notna(publish_complete_date):
            return publish_complete_date + timedelta(days=15)
        else:
            return pd.NaT

    else:
        return pd.NaT


def yes_no_based_on_status(status, positive_statuses):
    if status in positive_statuses:
        return "Yes"
    else:
        return "No"


def assign_archive_qc_status(archive_status):
    if archive_status == "Archived":
        return "QC Complete"
    elif archive_status == "Ready for Archive":
        return "Pending QC"
    else:
        return "Not Started"


def assign_archive_owner():
    return "Regulatory Operations / Publishing Archive Owner"

archive_rows = []

for index, row in archive_base.iterrows():

    submission_id = row.get("Submission_ID", "")
    publishing_id = row.get("Publishing_ID", f"PUB-{index+1:04d}")

    product_name = get_first_available(
        row,
        ["Product_Name_Publishing", "Product_Name_Submission", "Product_Name"],
        "Novalex"
    )

    variation_category = get_first_available(
        row,
        ["Variation_Category_Publishing", "Variation_Category_Submission", "Variation_Category", "Submission_Category"],
        ""
    )

    submission_title = get_first_available(
        row,
        ["Submission_Title_Publishing", "Submission_Title_Submission", "Submission_Title"],
        ""
    )

    submission_status = get_first_available(
        row,
        ["Submission_Status_Publishing", "Submission_Status_Submission", "Submission_Status"],
        ""
    )

    sequence_number = row.get("Sequence_Number", "")
    submission_format = row.get("Submission_Format", "eCTD")
    publishing_status = row.get("Publishing_Status", "")
    final_package_status = row.get("Final_Package_Status", "")
    validation_status = row.get("Validation_Status", "")
    gateway_status = row.get("Gateway_Submission_Status", "")
    acknowledgement_received = row.get("Acknowledgement_Received", "")

    health_authority = get_first_available(
        row,
        ["Health_Authority_Publishing", "Health_Authority_Submission", "Health_Authority"],
        "EMA"
    )

    actual_submission_date = get_first_available(
        row,
        ["Actual_Submission_Date"],
        pd.NaT
    )

    approval_date = get_first_available(
        row,
        ["Approval_Decision_Date", "Approval_Date"],
        pd.NaT
    )

    publish_complete_date = row.get("Publish_Complete_Date", pd.NaT)
    total_agency_queries = row.get("Total_Agency_Queries", 0)

    archive_status = assign_archive_status(
        submission_status,
        publishing_status,
        final_package_status
    )

    archive_date = assign_archive_date(
        archive_status,
        publish_complete_date,
        actual_submission_date,
        approval_date
    )

    final_dossier_available = "Yes" if final_package_status == "Final Package Available" else "No"

    validation_report_available = "Yes" if validation_status in [
        "Passed",
        "Passed with Minor Comments"
    ] else "No"

    gateway_ack_available = "Yes" if acknowledgement_received == "Yes" else "No"

    agency_correspondence_available = "Yes" if total_agency_queries > 0 else "No"

    approval_letter_available = "Yes" if submission_status in [
        "Archived",
        "Implemented",
        "Approved - Pending Implementation",
        "Implementation Overdue"
    ] else "No"

    archive_qc_status = assign_archive_qc_status(archive_status)
    archive_owner = assign_archive_owner()

    archive_rows.append({
        "Archive_ID": f"ARC-{index+1:04d}",
        "Submission_ID": submission_id,
        "Publishing_ID": publishing_id,
        "Product_Name": product_name,
        "Variation_Category": variation_category,
        "Submission_Title": submission_title,
        "Sequence_Number": sequence_number,
        "Health_Authority": health_authority,
        "Submission_Format": submission_format,
        "Submission_Status": submission_status,
        "Publishing_Status": publishing_status,
        "Validation_Status": validation_status,
        "Gateway_Submission_Status": gateway_status,
        "Submission_Date": actual_submission_date,
        "Approval_Date": approval_date,
        "Archive_Date": archive_date,
        "Archive_Status": archive_status,
        "Final_Dossier_Available": final_dossier_available,
        "Validation_Report_Available": validation_report_available,
        "Gateway_Acknowledgement_Available": gateway_ack_available,
        "Agency_Correspondence_Available": agency_correspondence_available,
        "Approval_Letter_Available": approval_letter_available,
        "Total_Agency_Queries": total_agency_queries,
        "Archive_QC_Status": archive_qc_status,
        "Archive_Owner": archive_owner,
        "Comments": ""
    })

archive_tracker = pd.DataFrame(archive_rows)

output_file = "Novalex_Archive_Tracker.xlsx"
archive_tracker.to_excel(output_file, index=False)

print("Archive Tracker created successfully!")
print("Output file:", output_file)
print("Rows created:", len(archive_tracker))

display(archive_tracker.head(20))

archive_tracker["Archive_Status"].value_counts()

display(archive_tracker[[
    "Archive_ID",
    "Submission_ID",
    "Sequence_Number",
    "Submission_Status",
    "Archive_Status",
    "Final_Dossier_Available",
    "Validation_Report_Available",
    "Agency_Correspondence_Available",
    "Approval_Letter_Available",
    "Archive_QC_Status"
]].head(30))

from google.colab import files

files.download("Novalex_Archive_Tracker.xlsx")

import pandas as pd

files = {
    "EMA Variations Master Database": "EMA Variations Master Database.xlsx",
    "Novalex Submission Tracker": "Novalex Submission Tracker.xlsx",
    "Novalex Agency Query Tracker": "Novalex Agency Query Tracker.xlsx",
    "Novalex Content Plan Tracker": "Novalex_Content_Plan_Tracker.xlsx",
    "Novalex Document Lifecycle Tracker": "Novalex_Document_Lifecycle_Tracker.xlsx",
    "Novalex Publishing Tracker": "Novalex_Publishing_Tracker.xlsx",
    "Novalex Archive Tracker": "Novalex_Archive_Tracker.xlsx",
    "Novalex Timeline": "Novalex timeline.xlsx"
}

dictionary_rows = []

for table_name, file_path in files.items():
    df = pd.read_excel(file_path)

    for col in df.columns:
        sample_value = df[col].dropna().iloc[0] if not df[col].dropna().empty else ""

        dictionary_rows.append({
            "File_Name": file_path,
            "Table_Name": table_name,
            "Column_Name": col,
            "Column_Description": "",
            "Data_Type": str(df[col].dtype),
            "Example_Value": sample_value,
            "Mandatory": "",
            "Source_or_Logic": "",
            "Used_In_Dashboard": "",
            "Notes": ""
        })

data_dictionary = pd.DataFrame(dictionary_rows)

output_file = "Novalex_Data_Dictionary.xlsx"
data_dictionary.to_excel(output_file, index=False)

print("Data Dictionary created successfully!")
print("Rows created:", len(data_dictionary))

display(data_dictionary.head(30))

import os

os.listdir()

import os

os.listdir()

files = {
    "EMA Variations Master Database": "EMA Variations Master Database.xlsx",
    "Novalex Submission Tracker": "Novalex Submission Tracker.xlsx",
    "Novalex Agency Query Tracker": "Novalex Agency Query Tracker.xlsx",
    "Novalex Content Plan Tracker": "Novalex_Content_Plan_Tracker.xlsx",
    "Novalex Document Lifecycle Tracker": "Novalex_Document_Lifecycle_Tracker.xlsx",
    "Novalex Publishing Tracker": "Novalex_Publishing_Tracker.xlsx",
    "Novalex Archive Tracker": "Novalex_Archive_Tracker.xlsx",
    "Novalex Timeline": "Novalex Timeline.xlsx"
}

import pandas as pd
import os

dictionary_rows = []

for table_name, file_path in files.items():

    if not os.path.exists(file_path):
        print(f"Skipping missing file: {file_path}")
        continue

    df = pd.read_excel(file_path)

    for col in df.columns:
        sample_value = df[col].dropna().iloc[0] if not df[col].dropna().empty else ""

        dictionary_rows.append({
            "File_Name": file_path,
            "Table_Name": table_name,
            "Column_Name": col,
            "Column_Description": "",
            "Data_Type": str(df[col].dtype),
            "Example_Value": sample_value,
            "Mandatory": "",
            "Source_or_Logic": "",
            "Used_In_Dashboard": "",
            "Notes": ""
        })

data_dictionary = pd.DataFrame(dictionary_rows)

output_file = "Novalex_Data_Dictionary.xlsx"
data_dictionary.to_excel(output_file, index=False)

print("Data Dictionary created successfully!")
print("Rows created:", len(data_dictionary))

display(data_dictionary.head(30))

data_dictionary["Table_Name"].value_counts()

import os

for file in os.listdir():
    print(file)

import pandas as pd
import os

for file in os.listdir():
    if file.endswith(".xlsx"):
        try:
            df = pd.read_excel(file)
            print("Readable:", file, "| rows:", df.shape[0], "| columns:", df.shape[1])
        except Exception as e:
            print("Not readable:", file, "| error:", e)

files = {
    "EMA Variations Master Database": "EMA Variations Master Database.xlsx",
    "Novalex Submission Tracker": "Novalex Submission Tracker.xlsx",
    "Novalex Agency Query Tracker": "Novalex Agency Query Tracker.xlsx",
    "Novalex Content Plan Tracker": "Novalex_Content_Plan_Tracker.xlsx",
    "Novalex Document Lifecycle Tracker": "Novalex_Document_Lifecycle_Tracker.xlsx",
    "Novalex Publishing Tracker": "Novalex_Publishing_Tracker.xlsx",
    "Novalex Archive Tracker": "Novalex_Archive_Tracker.xlsx",
    "Novalex Timeline": "Novalex timeline.xlsx"
}

dictionary_rows = []

for table_name, file_path in files.items():
    df = pd.read_excel(file_path)

    for col in df.columns:
        sample_value = df[col].dropna().iloc[0] if not df[col].dropna().empty else ""

        dictionary_rows.append({
            "File_Name": file_path,
            "Table_Name": table_name,
            "Column_Name": col,
            "Column_Description": "",
            "Data_Type": str(df[col].dtype),
            "Example_Value": sample_value,
            "Mandatory": "",
            "Source_or_Logic": "",
            "Used_In_Dashboard": "",
            "Notes": ""
        })

data_dictionary = pd.DataFrame(dictionary_rows)

output_file = "Novalex_Data_Dictionary.xlsx"
data_dictionary.to_excel(output_file, index=False)

print("Data Dictionary created successfully!")
print("Rows created:", len(data_dictionary))

display(data_dictionary.head(30))

from google.colab import files

files.download("Novalex_Data_Dictionary.xlsx")

import pandas as pd
import os

excel_files = [file for file in os.listdir() if file.endswith(".xlsx")]

dictionary_rows = []

for file_path in excel_files:
    table_name = file_path.replace(".xlsx", "")

    try:
        df = pd.read_excel(file_path)

        for col in df.columns:
            sample_value = df[col].dropna().iloc[0] if not df[col].dropna().empty else ""

            dictionary_rows.append({
                "File_Name": file_path,
                "Table_Name": table_name,
                "Column_Name": col,
                "Column_Description": "",
                "Data_Type": str(df[col].dtype),
                "Example_Value": sample_value,
                "Mandatory": "",
                "Source_or_Logic": "",
                "Used_In_Dashboard": "",
                "Notes": ""
            })

    except Exception as e:
        print("Skipped:", file_path, "| Error:", e)

data_dictionary = pd.DataFrame(dictionary_rows)

output_file = "Novalex_Data_Dictionary.xlsx"
data_dictionary.to_excel(output_file, index=False)

print("Data Dictionary created successfully!")
print("Files included:")
print(data_dictionary["File_Name"].unique())

display(data_dictionary.head(30))

from google.colab import files
files.download("Novalex_Data_Dictionary.xlsx")

import pandas as pd

relationship_rows = [
    {
        "Relationship_ID": "REL-001",
        "From_Table": "EMA Variations Master Database",
        "From_Column": "Variation_Category / Classification_Code",
        "To_Table": "Novalex Submission Tracker",
        "To_Column": "Variation_Category / Trigger_ID",
        "Relationship_Type": "Reference / Lookup",
        "Cardinality": "Many-to-One",
        "Power_BI_Relationship": "Optional",
        "Purpose": "Uses EMA variation rules as reference logic for classifying submissions",
        "Notes": "Use this mainly as a lookup/reference table, not always a direct relationship unless IDs match cleanly"
    },
    {
        "Relationship_ID": "REL-002",
        "From_Table": "Novalex Submission Tracker",
        "From_Column": "Submission_ID",
        "To_Table": "Novalex Content Plan Tracker",
        "To_Column": "Submission_ID",
        "Relationship_Type": "Primary Relationship",
        "Cardinality": "One-to-Many",
        "Power_BI_Relationship": "Required",
        "Purpose": "Links each submission to its required CTD content plan items",
        "Notes": "This is one of the most important relationships"
    },
    {
        "Relationship_ID": "REL-003",
        "From_Table": "Novalex Content Plan Tracker",
        "From_Column": "Content_Plan_ID",
        "To_Table": "Novalex Document Lifecycle Tracker",
        "To_Column": "Content_Plan_ID",
        "Relationship_Type": "Primary Relationship",
        "Cardinality": "One-to-One / One-to-Many",
        "Power_BI_Relationship": "Required",
        "Purpose": "Links each content plan item to its controlled document lifecycle record",
        "Notes": "Usually one content plan item creates one document record in your project"
    },
    {
        "Relationship_ID": "REL-004",
        "From_Table": "Novalex Submission Tracker",
        "From_Column": "Submission_ID",
        "To_Table": "Novalex Document Lifecycle Tracker",
        "To_Column": "Submission_ID",
        "Relationship_Type": "Supporting Relationship",
        "Cardinality": "One-to-Many",
        "Power_BI_Relationship": "Optional",
        "Purpose": "Allows submission-level document status reporting",
        "Notes": "Use if Power BI relationship via Content Plan becomes complex"
    },
    {
        "Relationship_ID": "REL-005",
        "From_Table": "Novalex Submission Tracker",
        "From_Column": "Submission_ID",
        "To_Table": "Novalex Publishing Tracker",
        "To_Column": "Submission_ID",
        "Relationship_Type": "Primary Relationship",
        "Cardinality": "One-to-One",
        "Power_BI_Relationship": "Required",
        "Purpose": "Links each submission to its eCTD publishing sequence and validation status",
        "Notes": "Each submission should have one publishing record"
    },
    {
        "Relationship_ID": "REL-006",
        "From_Table": "Novalex Publishing Tracker",
        "From_Column": "Publishing_ID",
        "To_Table": "Novalex Archive Tracker",
        "To_Column": "Publishing_ID",
        "Relationship_Type": "Primary Relationship",
        "Cardinality": "One-to-One",
        "Power_BI_Relationship": "Required",
        "Purpose": "Links the final published package to its archive record",
        "Notes": "Use this to track final dossier archival"
    },
    {
        "Relationship_ID": "REL-007",
        "From_Table": "Novalex Submission Tracker",
        "From_Column": "Submission_ID",
        "To_Table": "Novalex Agency Query Tracker",
        "To_Column": "Submission_ID",
        "Relationship_Type": "Primary Relationship",
        "Cardinality": "One-to-Many",
        "Power_BI_Relationship": "Required",
        "Purpose": "Links each submission to health authority query rounds",
        "Notes": "Use this for query dashboards and overdue response tracking"
    },
    {
        "Relationship_ID": "REL-008",
        "From_Table": "Novalex Submission Tracker",
        "From_Column": "Submission_ID",
        "To_Table": "Novalex Archive Tracker",
        "To_Column": "Submission_ID",
        "Relationship_Type": "Supporting Relationship",
        "Cardinality": "One-to-One",
        "Power_BI_Relationship": "Optional",
        "Purpose": "Allows direct submission-to-archive reporting",
        "Notes": "Helpful for archive status visuals"
    },
    {
        "Relationship_ID": "REL-009",
        "From_Table": "Novalex Timeline",
        "From_Column": "Lifecycle_Stage / Event_ID",
        "To_Table": "Novalex Submission Tracker",
        "To_Column": "Lifecycle_Stage / Submission_ID",
        "Relationship_Type": "Context Relationship",
        "Cardinality": "Many-to-Many / Reference",
        "Power_BI_Relationship": "Optional",
        "Purpose": "Provides lifecycle context for drug development and post-authorisation activities",
        "Notes": "Timeline can be used as a separate dashboard page if direct IDs do not match"
    }
]

relationship_map = pd.DataFrame(relationship_rows)

output_file = "Novalex_Relationship_Map.xlsx"
relationship_map.to_excel(output_file, index=False)

print("Relationship Map created successfully!")
print("Rows created:", len(relationship_map))

display(relationship_map)

from google.colab import files

files.download("Novalex_Relationship_Map.xlsx")